### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by sta4-l0rd** [multiplemonomials/CMakeTraining#1]
Hello Sir, 
I really need to see the remaining sessions on CMake, I cant find it on your [YT channel](https://www.youtube.com/channel/UCtd3FPx6DjD3dV9R-mTnLWA)
Please HELP

**Comment by jeethesh-pai** [comment]
Hi did you find the rest of the sessions?

Thanks

**Comment by multiplemonomials** [comment]
Apologies, I've gotten pretty busy and have not gotten around to making them.  It's still on my todo list for someday though.
